server:
  port: 8080

spring:
  application:
    name: spring-ai-demo
  autoconfigure:
    exclude:
      - dev.langchain4j.openai.spring.AutoConfig   # shutdown the autoconfig of langchain4j, same bean called openAiChatModel
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.2
      embedding:
        options:
          model: text-embedding-3-small
    model:
      image: stabilityai
    stabilityai:
      api-key: ${STABILITY_API_KEY}
      image:
        options:
          model: stable-diffusion-xl-1024-v1-0
          width: 768
          height: 768
          N: 1